apiVersion: apps/v1
kind: Deployment
metadata:
  name: serverless-deployment
  labels:
    app: serverless
spec:
  replicas: 1
  selector:
    matchLabels:
      app: serverless
  template:
    metadata:
      labels:
        app: serverless
    spec:
      containers:
      - name: serverless
        image: plsmaop/serverless:flask
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /home/ivan/fuse
          name: crail-test
        env:
        - name: AWS_SECRET_ACCESS_KEY
          value: "WmxCN3zNS4cU/BdQvHjEk24cFTCdUXfySr2CESOc"
        - name: AWS_ACCESS_KEY_ID
          value: "AKIA5ZFDMBZWXSAOABEJ"
      volumes:
      - name: crail-test
        persistentVolumeClaim:
          claimName: local-crail-fuse
          readOnly: false

---

apiVersion: v1
kind: Service
metadata:
  name: serverless-service
spec:
  selector:
    app: serverless
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

---

apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: serverless-vs
spec:
  gateways:
  - istio-system/ingressgateway
  hosts:
  - serverless2.default.140.112.90.44.xip.io
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: serverless-service.default.svc.cluster.local
        port:
          number: 8080

--- 

apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-crail-fuse
spec:
  accessModes:
  - ReadWriteOnce
  - ReadWriteMany
  capacity:
    storage: 10Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: local-crail-fuse
    namespace: default
  local:
    path: /home/ivan/fuse
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - rdma1
          - rdma2
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-volume
  volumeMode: Filesystem

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-crail-fuse
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-volume
  volumeMode: Filesystem
  volumeName: local-crail-fuse